<a href="https://colab.research.google.com/github/AdityaMohanty374/LLM-from-Scratch/blob/master/Working_with_Text_Data(Input_Pipeline_Stream).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install uv

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 50.2 MB/s eta 0:00:00


In [ ]:
!uv pip install -r https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/refs/heads/main/requirements.txt

Using Python 3.11.13 environment at: /usr
Resolved 147 packages in 942ms
⠙ Preparing packages... (0/29)
⠙ Preparing packages... (0/29)
⠙ Preparing packages... (0/29)
python-json-logger   ------------------------------     0 B/14.81 KiB
⠙ Preparing packages... (0/29)
python-json-logger       ------------------------------     0 B/14.81 KiB
⠙ Preparing packages... (0/29)
python-json-logger       ------------------------------     0 B/14.81 KiB
⠙ Preparing packages... (0/29)
jupyter-server-terminals ------------------------------     0 B/13.34 KiB
python-json-logger       ------------------------------     0 B/14.81 KiB
⠙ Preparing packages... (0/29)
jupyter-server-terminals ------------------------------     0 B/13.34 KiB
python-json-logger       ------------------------------     0 B/14.81 KiB
⠙ Preparing packages... (0/29)
jupyter-server-terminals ------------------------------     0 B/13.34 KiB
python-json-logger       ------------------------------     0 B/14.81 KiB
⠙ Preparing packa

In [ ]:
!uv pip install -r https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/refs/heads/main/requirements.txt --system

Using Python 3.11.13 environment at: /usr
Audited 9 packages in 148ms


In [31]:
import os
import urllib.request

if not os.path.exists("the-verdict.txt"):
  url = ("https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/refs/heads/main/ch02/01_main-chapter-code/the-verdict.txt")
  file_path = "the-verdict.txt"
  urllib.request.urlretrieve(url, file_path)

In [32]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

In [33]:
raw_text

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [34]:
len(raw_text)

20479

In [35]:
import re

text = "Hello, a test."
result = re.split(r'([.,]|\s)', text)#spilts each words, spaces, special characs
print(result)
result = [item.strip() for item in result if item.strip()]#removes the spaces from splits
print(result)

['Hello', ',', '', ' ', 'a', ' ', 'test', '.', '']
['Hello', ',', 'a', 'test', '.']


In [36]:
#more advanced tokenizer

text = "Hello, world. Is this-- a test?"
result = re.split(r'([,.:;?_!"()\')]|--|\s)',text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


In [37]:
#for the train data
result = re.split(r'([,.:;?_!"()\')]|--|\s)',raw_text)
result = [item.strip() for item in result if item.strip()]
print(result)

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--', 'deploring', 'his', 'unaccountable', 'abdication', '.', '"', 'Of', 'course', 'it', "'", 's', 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'", 'way', 'up', ';', 'but', 'I', 'don', "'", 't', 'think', 'of', 'that', ',

In [38]:
len(result)

4690

In [39]:
#converting the tokens to tokenIDS
#finding the unique tokens
all_words = sorted(set(result))
print(all_words)

['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed', 'Devonshire', 'Don', 'Dubarry', 'Emperors', 'Florence', 'For', 'Gallery', 'Gideon', 'Gisburn', 'Gisburns', 'Grafton', 'Greek', 'Grindle', 'Grindles', 'HAD', 'Had', 'Hang', 'Has', 'He', 'Her', 'Hermia', 'His', 'How', 'I', 'If', 'In', 'It', 'Jack', 'Jove', 'Just', 'Lord', 'Made', 'Miss', 'Money', 'Monte', 'Moon-dancers', 'Mr', 'Mrs', 'My', 'Never', 'No', 'Now', 'Nutley', 'Of', 'Oh', 'On', 'Once', 'Only', 'Or', 'Perhaps', 'Poor', 'Professional', 'Renaissance', 'Rickham', 'Riviera', 'Rome', 'Russian', 'Sevres', 'She', 'Stroud', 'Strouds', 'Suddenly', 'That', 'The', 'Then', 'There', 'They', 'This', 'Those', 'Though', 'Thwing', 'Thwings', 'To', 'Usually', 'Venetian', 'Victor', 'Was', 'We', 'Well', 'What', 'When', 'Why', 'Yes', 'You', '_', 'a', 'abdication', 'able', 'about', 'above',

In [40]:
len(all_words)

1130

In [41]:
vocab_size = len(all_words)

In [42]:
#iterate over vocab_size to assign ids to each item inside all_words incrementingly
vocab = {token:integer for integer, token in enumerate(all_words)}
print(vocab)

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte': 64, 'Moon-dancers': 65, 'Mr': 66, 'Mrs': 67, 'My': 68, 'Never': 69, 'No': 70, 'Now': 71, 'Nutley': 72, 'Of': 73, 'Oh': 74, 'On': 75, 'Once': 76, 'Only': 77, 'Or': 78, 'Perhaps': 79, 'Poor': 80, 'Professional': 81, 'Renaissance': 82, 'Ri

In [43]:
#simple tokenizer class
class SimpleTokenizerV1:
    def __init__(self, vocab):
      #mapping strings to integer in vocab
        self.str_to_int = vocab
      #mapping integers to strings in vocab
        self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):
      #text to token
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
      #remove white spaces
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
      #assign the ids
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
      #assign words from the ids
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [44]:
tokenizer = SimpleTokenizerV1(vocab)

In [45]:
text = """"It's the last he painted, you know,"
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
s = tokenizer.decode(ids)
print(ids)
print(s)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]
" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


CANT HANDLE UNKNOWN TOKENS

In [48]:
text = "Hello, do you like tea. Is this-- a test?"
#error on hello as its unknown to the vocab
tokenizer.encode(text)

KeyError: 'Hello'

In [49]:
all_tokens = sorted(list(set(result)))
#added unknown element and end of sentence token
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

In [50]:
len(vocab)

1132

In [51]:
for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [52]:
#newer version of the simple tokenizer
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        #if the item is present in the vocab then return its token if not return i
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]

        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

In [53]:
tokenizer = SimpleTokenizerV2(vocab)
ids = tokenizer.encode(text)
tokenizer.decode(ids)

'<|unk|>, do you like tea. <|unk|> this -- a <|unk|>?'

# **BYTE PAIR ENCODING(BPE)**


In [54]:
#using gpt2's own tokenizer tiktoken

import tiktoken
tiktoken.__version__
tokenizer = tiktoken.get_encoding("gpt2")
tokenizer.encode("Hello World!")

[15496, 2159, 0]

In [55]:
tokenizer.decode(tokenizer.encode("Hello World!"))

'Hello World!'

In [56]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


# **DATA SAMPLING USING SLIDING WINDOW**

In [57]:
#generating new tokens using tiktoken
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [58]:
#we remove the first 50 tokens for interesting result later
enc_sample = enc_text[50:]
context_size = 4 #generally in 1000s for production level LLMs

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:      {y}")

x: [290, 4920, 2241, 287]
y:      [4920, 2241, 287, 257]


In [59]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print((context), "---->", (desired))

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


In [60]:
import torch
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [61]:
def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [62]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [63]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [64]:
#stride length determines if the tokens r repeated or not
#here its not repeated on a length of 4
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


# **Create TOKEN EMBEDDING**

In [65]:
#Suppose we have the following four input examples with input ids 2, 3, 5, and 1 (after tokenization):
input_ids = torch.tensor([2, 3, 5, 1])

In [66]:
#For the sake of simplicity, suppose we have a small
#vocabulary of only 6 words and we want to create embeddings of size 3,
#This would result in a 6x3 weight matrix
vocab_size = 50257  #not using 6 instead 50257 as its more pratical( BytePair encoder )
output_dim = 256   #not using 3 instead 256 as more pratical

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035,  ...,  1.3337,  0.0771, -0.0522],
        [ 0.2386,  0.1411, -1.3354,  ..., -0.0315, -1.0640,  0.9417],
        [-1.3152, -0.0677, -0.1350,  ..., -0.3181, -1.3936,  0.5226],
        ...,
        [ 0.5871, -0.0572, -1.1628,  ..., -0.6887, -0.7364,  0.4479],
        [ 0.4438,  0.7411,  1.1263,  ...,  1.2091,  0.6781,  0.3331],
        [-0.2537,  0.1446,  0.7203,  ..., -0.2134,  0.2144,  0.3006]],
       requires_grad=True)


In [67]:
#To convert a token with id 3 into a 3-dimensional vector, we do the following:
print(embedding_layer(torch.tensor([3])))

tensor([[ 0.2579,  0.3420, -0.8168,  1.6772, -0.8353,  0.7531,  0.0821,  1.1650,
         -0.6635, -0.7809, -0.2270, -0.4358,  0.8209, -0.6353, -0.4386, -0.4472,
          1.5098, -0.0783,  0.7707,  0.5180,  0.2458,  0.3937, -0.7882,  0.3228,
         -0.7447,  0.3102, -1.4619, -0.1745, -0.5482, -0.4097, -0.0627,  0.0175,
          1.3715, -0.2226,  1.0566,  0.3687,  1.8359,  1.2957,  0.8045, -0.6188,
         -1.1795,  0.3383,  0.9319,  0.7436,  0.2490, -1.3814, -0.7985,  0.6369,
         -1.5530, -1.6292,  0.6107,  1.2718, -0.9422, -0.2667, -0.3216,  0.4504,
          0.3718,  0.6457,  0.5804,  0.3752,  0.4293, -0.7276, -0.5527,  0.6189,
         -1.4284,  0.5617,  0.7701,  0.3566, -0.1267,  0.9447,  0.1466,  0.2673,
          0.9467, -0.1406,  0.0329, -2.1542,  1.3953,  1.1845, -0.1255,  0.2517,
          1.3081,  0.1495,  1.1315,  0.2044,  1.2430, -0.0409,  0.7491,  0.3026,
         -0.7591, -0.9542, -1.6160, -0.1016, -1.1510, -1.8215,  1.1655, -2.3307,
          0.5062, -1.5363, -

In [68]:
#for all input ids
print(embedding_layer(input_ids))

tensor([[-1.3152, -0.0677, -0.1350,  ..., -0.3181, -1.3936,  0.5226],
        [ 0.2579,  0.3420, -0.8168,  ..., -0.4840, -0.2713, -0.0774],
        [-0.3162,  1.2700, -0.0903,  ..., -0.4098,  0.4978, -0.3721],
        [ 0.2386,  0.1411, -1.3354,  ..., -0.0315, -1.0640,  0.9417]],
       grad_fn=<EmbeddingBackward0>)


# **Encoding word positions**

In [69]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [70]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [71]:
token_embeddings = embedding_layer(inputs)
token_embeddings.shape

torch.Size([8, 4, 256])

In [72]:
token_embeddings[0, 0]

tensor([-6.3964e-02,  3.3174e-01,  1.0698e-01, -1.4281e-01, -3.0141e-01,
        -6.3647e-01, -2.2577e+00,  8.0754e-01,  1.2420e+00, -7.9977e-01,
         1.3265e+00, -1.3640e+00, -1.4752e+00, -1.0095e-01, -1.5406e+00,
        -9.0417e-01, -1.2689e-01,  9.2804e-01,  5.6544e-01, -1.8898e-01,
        -1.2679e-01,  4.5306e-01, -7.6017e-01, -1.0059e+00, -9.2078e-01,
         8.7217e-01,  1.8234e+00, -1.9416e+00,  1.0657e+00,  3.9532e-01,
         5.7309e-01, -7.7677e-01, -1.3191e+00, -6.6007e-01,  4.9130e-01,
         1.1239e+00,  1.4588e+00, -3.6530e-01, -4.0372e-02,  1.9042e-01,
        -1.1572e+00, -1.1329e+00,  2.7644e-01,  6.3706e-01, -1.5947e+00,
        -2.6210e-02, -1.4804e+00, -1.0301e+00, -1.3259e+00, -8.9009e-01,
         1.8119e+00,  1.9705e+00,  1.6373e-01, -5.1866e-01,  5.2069e-01,
        -1.0986e+00,  1.3451e+00, -2.5956e-01,  1.2858e+00, -1.9670e+00,
         9.2041e-02,  4.5699e-01, -1.4753e+00, -4.4934e-01,  1.8373e+00,
        -1.1507e+00, -6.0601e-01, -5.3533e-01, -2.9

In [73]:
#adding positional informations
#GPT-2 uses absolute position embeddings, so we just create another embedding layer, similar to the
#token embedding layer
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
print(pos_embedding_layer.weight)

Parameter containing:
tensor([[-1.4150, -0.3142,  0.2827,  ...,  0.8155, -0.1085, -1.1927],
        [-1.9800,  0.0610, -0.0494,  ..., -0.6422,  0.5716, -1.1329],
        [ 1.0052,  1.7802,  1.2652,  ..., -1.1619, -0.1109,  1.0411],
        [ 0.3760, -0.3758, -0.0484,  ...,  0.1080,  0.3852,  1.0876]],
       requires_grad=True)


In [74]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)
print(pos_embeddings)

torch.Size([4, 256])
tensor([[-1.4150, -0.3142,  0.2827,  ...,  0.8155, -0.1085, -1.1927],
        [-1.9800,  0.0610, -0.0494,  ..., -0.6422,  0.5716, -1.1329],
        [ 1.0052,  1.7802,  1.2652,  ..., -1.1619, -0.1109,  1.0411],
        [ 0.3760, -0.3758, -0.0484,  ...,  0.1080,  0.3852,  1.0876]],
       grad_fn=<EmbeddingBackward0>)


In [75]:
#To create the input embeddings used in an LLM
#we simply add the token and the positional embeddings
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)
print(input_embeddings)

torch.Size([8, 4, 256])
tensor([[[-1.4789e+00,  1.7579e-02,  3.8972e-01,  ...,  1.3504e+00,
          -9.1092e-01, -3.5165e+00],
         [-2.3324e+00,  4.1186e-01,  9.3785e-01,  ..., -2.4888e+00,
          -1.1318e+00, -8.1060e-01],
         [ 2.0069e+00,  2.7101e+00,  1.8634e-03,  ..., -2.3875e+00,
           1.0070e+00,  1.1753e+00],
         [ 1.1756e+00,  1.9079e+00, -7.0086e-01,  ..., -1.0136e+00,
           8.5575e-01,  1.2408e+00]],

        [[-1.5232e+00, -1.5865e+00, -9.3895e-01,  ..., -1.0444e-01,
           1.8989e+00, -2.6065e+00],
         [-2.2227e+00,  9.7547e-01,  1.0391e+00,  ..., -1.5073e+00,
           4.0985e+00, -4.1040e-01],
         [ 4.6181e-01,  3.4006e+00,  2.4874e+00,  ..., -4.8047e-01,
          -1.5141e+00,  1.1903e+00],
         [ 2.5676e-02, -1.3083e+00, -1.3384e+00,  ..., -1.3900e+00,
           5.2514e-01,  1.4606e+00]],

        [[-1.3473e+00, -1.3899e+00,  4.1981e-01,  ...,  4.2434e-01,
          -1.2059e+00, -4.3363e-01],
         [-3.2361e+00,  3.7